"""Vertex AI Vector Search vector store — upsert, query, and delete document chunks.

Vector IDs use the `chunk_id` field generated by the chunker.

Architecture note
-----------------
Vertex AI Vector Search stores vectors only — unlike Pinecone it has no built-in
metadata store. A local SQLite database (VECTOR_METADATA_DB_PATH) stores chunk
text and metadata (source, section, page) keyed by chunk_id.

TODO: Replace the local SQLite metadata store with Google Cloud Firestore
      (`google-cloud-firestore`) for multi-instance deployments where the local
      filesystem is not shared between replicas (e.g. Cloud Run, GKE).

Score semantics
---------------
The index is created with DOT_PRODUCT_DISTANCE. Because text-embedding-004 returns
unit-normalised vectors, dot_product == cosine_similarity ∈ [-1, 1].
`neighbor.distance` maps directly to the retrieval_score_threshold (default 0.75)
with no conversion needed.

One-time setup
--------------
The Vertex AI Vector Search index and endpoint must be created before first use.
Run `python scripts/setup_vertex_index.py` once to create and deploy the index,
then copy the printed IDs into your .env file.
"""

import logging
import sqlite3
from pathlib import Path
from typing import Any

import vertexai
from google.cloud import aiplatform
from google.oauth2 import service_account

from config.settings import get_settings
from embeddings.embedder import embed, embed_query

logger = logging.getLogger(__name__)

_DIMENSION = 768  # text-embedding-004 output dimension
_VERTEX_SCOPES = ["https://www.googleapis.com/auth/cloud-platform"]
_BATCH_SIZE = 100


# ── Credentials ───────────────────────────────────────────────────────────────


def _get_credentials() -> service_account.Credentials:
    settings = get_settings()
    return service_account.Credentials.from_service_account_file(
        settings.google_service_account_json_path,
        scopes=_VERTEX_SCOPES,
    )


def _init_aiplatform() -> None:
    settings = get_settings()
    credentials = _get_credentials()
    aiplatform.init(
        project=settings.google_cloud_project,
        location=settings.google_cloud_location,
        credentials=credentials,
    )


# ── Vertex AI resources ───────────────────────────────────────────────────────


def _get_index() -> aiplatform.MatchingEngineIndex:
    """Return the configured Vertex AI Vector Search index."""
    _init_aiplatform()
    settings = get_settings()
    return aiplatform.MatchingEngineIndex(
        index_name=settings.vertex_vector_search_index_id
    )


def _get_endpoint() -> aiplatform.MatchingEngineIndexEndpoint:
    """Return the configured Vertex AI Vector Search index endpoint."""
    _init_aiplatform()
    settings = get_settings()
    return aiplatform.MatchingEngineIndexEndpoint(
        index_endpoint_name=settings.vertex_vector_search_endpoint_id
    )


# ── SQLite metadata store ─────────────────────────────────────────────────────


def _get_db_path() -> Path:
    path = Path(get_settings().vector_metadata_db_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def _get_db() -> sqlite3.Connection:
    """Open (and initialise if new) the local metadata SQLite database."""
    conn = sqlite3.connect(str(_get_db_path()))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS chunk_metadata (
            chunk_id TEXT PRIMARY KEY,
            text     TEXT NOT NULL,
            source   TEXT NOT NULL,
            section  TEXT NOT NULL,
            page     INTEGER
        )
        """
    )
    conn.commit()
    return conn


# ── Public API ────────────────────────────────────────────────────────────────


def upsert_chunks(chunks: list[dict[str, Any]]) -> None:
    """Embed chunks, upsert vectors to Vertex AI, and store metadata in SQLite.

    Args:
        chunks: List of chunk dicts from the chunker. Each must have
            'chunk_id', 'text', 'source', 'section', and optionally 'page'.
    """
    if not chunks:
        return

    # ── Step 1: embed ──────────────────────────────────────────────────────
    texts = [c["text"] for c in chunks]
    vectors = embed(texts)

    # ── Step 2: upsert to Vertex AI Vector Search ──────────────────────────
    index = _get_index()
    datapoints = []
    for chunk, vector in zip(chunks, vectors):
        datapoints.append(
            aiplatform.gapic.IndexDatapoint(
                datapoint_id=chunk["chunk_id"],
                feature_vector=vector,
            )
        )

    for i in range(0, len(datapoints), _BATCH_SIZE):
        index.upsert_datapoints(datapoints=datapoints[i : i + _BATCH_SIZE])

    logger.info("Upserted %d vectors to Vertex AI Vector Search", len(datapoints))

    # ── Step 3: save metadata to SQLite ───────────────────────────────────
    conn = _get_db()
    try:
        conn.executemany(
            """
            INSERT OR REPLACE INTO chunk_metadata (chunk_id, text, source, section, page)
            VALUES (?, ?, ?, ?, ?)
            """,
            [
                (
                    c["chunk_id"],
                    c.get("text", ""),
                    c.get("source", ""),
                    c.get("section", ""),
                    c.get("page"),
                )
                for c in chunks
            ],
        )
        conn.commit()
    finally:
        conn.close()

    logger.debug("Saved metadata for %d chunks to SQLite", len(chunks))


def query(query_text: str, top_k: int | None = None) -> list[dict[str, Any]]:
    """Perform a similarity search against the Vertex AI Vector Search index.

    Args:
        query_text: The natural language query string.
        top_k: Number of nearest neighbours to return (defaults to settings.top_k_chunks).

    Returns:
        List of result dicts with keys: chunk_id, score, text, source, section, page.
        Chunks with no matching metadata in SQLite are silently skipped.
    """
    settings = get_settings()
    k = top_k or settings.top_k_chunks

    query_vector = embed_query(query_text)
    endpoint = _get_endpoint()

    response = endpoint.find_neighbors(
        deployed_index_id=settings.vertex_vector_search_deployed_index_id,
        queries=[query_vector],
        num_neighbors=k,
    )

    # response is list[list[MatchNeighbor]]; we sent one query so take index 0
    neighbors = response[0] if response else []

    # Fetch metadata from SQLite for returned chunk IDs
    chunk_ids = [n.id for n in neighbors]
    if not chunk_ids:
        return []

    conn = _get_db()
    try:
        placeholders = ",".join("?" * len(chunk_ids))
        rows = conn.execute(
            f"SELECT chunk_id, text, source, section, page FROM chunk_metadata WHERE chunk_id IN ({placeholders})",  # noqa: S608
            chunk_ids,
        ).fetchall()
    finally:
        conn.close()

    meta_by_id = {row[0]: row for row in rows}

    results: list[dict[str, Any]] = []
    for neighbor in neighbors:
        row = meta_by_id.get(neighbor.id)
        if row is None:
            logger.warning("No metadata found for chunk_id '%s', skipping", neighbor.id)
            continue
        results.append(
            {
                "chunk_id": row[0],
                "score": neighbor.distance,  # dot_product == cosine_similarity (unit vectors)
                "text": row[1],
                "source": row[2],
                "section": row[3],
                "page": row[4],
            }
        )

    logger.debug("Vector Search returned %d results for top_k=%d", len(results), k)
    return results


def delete_by_source(source_filename: str) -> None:
    """Delete all vectors and metadata for the given source filename.

    Args:
        source_filename: The 'source' value to match (e.g. 'my_sop.docx').
    """
    conn = _get_db()
    try:
        rows = conn.execute(
            "SELECT chunk_id FROM chunk_metadata WHERE source = ?", (source_filename,)
        ).fetchall()
        chunk_ids = [row[0] for row in rows]

        if not chunk_ids:
            logger.info("No chunks found for source '%s', nothing to delete", source_filename)
            return

        # Remove from Vertex AI Vector Search
        index = _get_index()
        for i in range(0, len(chunk_ids), _BATCH_SIZE):
            index.remove_datapoints(datapoint_ids=chunk_ids[i : i + _BATCH_SIZE])

        # Remove from SQLite metadata
        conn.execute(
            "DELETE FROM chunk_metadata WHERE source = ?", (source_filename,)
        )
        conn.commit()
    finally:
        conn.close()

    logger.info("Deleted %d vectors for source '%s'", len(chunk_ids), source_filename)
